server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    default-schema: public
  h2:
    console:
      enabled: true  #http://localhost:8083/h2-console
  jpa:               #http://localhost:8083
    show-sql: true     #http://46.56.82.33:8083  office
    hibernate:          #http://192.168.65.143:8083  VPNTOKEN
      ddl-auto: update  #http://10.16.67.49:8083   wifi  (но для телефона другая сеть wifi )

  http:
    encoding:
      charset: utf8
      enabled: true
      force: true