server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    default-schema: public
  h2:
    console:
      enabled: true  #http://localhost:8083/h2-console
  jpa:               #http://localhost:8083
    show-sql: true
    hibernate:
      ddl-auto: update

  http:
    encoding:
      charset: utf8
      enabled: true
      force: true